# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainPagebaOUVg.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from qt_core import *
from App.GetCamIndex import *

class Ui_AppPages(object):
    def setupUi(self, AppPages):
        if not AppPages.objectName():
            AppPages.setObjectName(u"AppPages")
        AppPages.resize(730, 600)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.LiveFeed = QLabel(self.page)
        self.LiveFeed.setObjectName(u"LiveFeed")
        self.LiveFeed.setGeometry(QRect(0, 20, 320, 240))
        self.LiveFeed.setMinimumSize(QSize(301, 191))
        self.LiveFeed.setFrameShape(QFrame.StyledPanel)
        self.LiveFeed.setFrameShadow(QFrame.Raised)
        self.LiveFeed.setAlignment(Qt.AlignCenter)
        self.LiveGraph = QLabel(self.page)
        self.LiveGraph.setObjectName(u"LiveGraph")
        self.LiveGraph.setGeometry(QRect(0, 290, 720, 300))
        self.LiveGraph.setMaximumSize(QSize(16777215, 16777215))
        self.LiveGraph.setMouseTracking(False)
        self.LiveGraph.setFrameShape(QFrame.StyledPanel)
        self.LiveGraph.setFrameShadow(QFrame.Raised)
        self.LiveGraph.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 320, 20))
        font = QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 270, 320, 20))
        self.label_2.setFont(font)
        self.line = QFrame(self.page)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(321, 20, 20, 240))
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setFrameShape(QFrame.VLine)
        self.CamList = QComboBox(self.page)
        self.CamList.setObjectName(u"CamList")
        self.CamList.setGeometry(QRect(70, 2, 151, 16))
        self.CamList.setEditable(False)
        self.CamList.setFrame(True)
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(340, 0, 251, 18))
        self.PixelRowEdit = QLineEdit(self.page)
        self.PixelRowEdit.setObjectName(u"PixelRowEdit")
        self.PixelRowEdit.setGeometry(QRect(457, 35, 30, 20))
        self.PixelRowEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(340, 100, 111, 20))
        self.CamSnap = QPushButton(self.page)
        self.CamSnap.setObjectName(u"CamSnap")
        self.CamSnap.setGeometry(QRect(360, 130, 91, 26))
        self.PixRowSlider = QSlider(self.page)
        self.PixRowSlider.setObjectName(u"PixRowSlider")
        self.PixRowSlider.setGeometry(QRect(350, 70, 351, 16))
        self.PixRowSlider.setAutoFillBackground(False)
        self.PixRowSlider.setMaximum(479)
        self.PixRowSlider.setValue(240)
        self.PixRowSlider.setTracking(True)
        self.PixRowSlider.setOrientation(Qt.Horizontal)
        self.PixRowSlider.setInvertedAppearance(False)
        self.PixRowSlider.setTickPosition(QSlider.NoTicks)
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(470, 100, 111, 20))
        self.GraphCSV = QPushButton(self.page)
        self.GraphCSV.setObjectName(u"GraphCSV")
        self.GraphCSV.setGeometry(QRect(500, 130, 71, 26))
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(340, 30, 111, 31))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.GraphSnap = QPushButton(self.page)
        self.GraphSnap.setObjectName(u"GraphSnap")
        self.GraphSnap.setGeometry(QRect(590, 130, 91, 26))
        self.ToggleCursor = QCheckBox(self.page)
        self.ToggleCursor.setObjectName(u"ToggleCursor")
        self.ToggleCursor.setGeometry(QRect(350, 180, 111, 24))
        self.AdCursor = QSlider(self.page)
        self.AdCursor.setObjectName(u"AdCursor")
        self.AdCursor.setEnabled(False)
        self.AdCursor.setGeometry(QRect(350, 215, 351, 16))
        self.AdCursor.setMaximum(639)
        self.AdCursor.setOrientation(Qt.Horizontal)
        self.ImgFlip = QRadioButton(self.page)
        self.ImgFlip.setObjectName(u"ImgFlip")
        self.ImgFlip.setGeometry(QRect(230, 0, 91, 17))
        self.label_10 = QLabel(self.page)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(350, 240, 111, 16))
        self.LNano = QLabel(self.page)
        self.LNano.setObjectName(u"LNano")
        self.LNano.setGeometry(QRect(460, 240, 51, 16))
        self.label_17 = QLabel(self.page)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(540, 240, 101, 16))
        self.LInt = QLabel(self.page)
        self.LInt.setObjectName(u"LInt")
        self.LInt.setGeometry(QRect(640, 240, 31, 16))
        AppPages.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.CamFeed = QLabel(self.page_2)
        self.CamFeed.setObjectName(u"CamFeed")
        self.CamFeed.setGeometry(QRect(150, 30, 400, 300))
        self.CamFeed.setMouseTracking(False)
        self.CamFeed.setFrameShape(QFrame.Box)
        self.CamFeed.setAlignment(Qt.AlignCenter)
        self.line_2 = QFrame(self.page_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 340, 701, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.CamSlide2 = QSlider(self.page_2)
        self.CamSlide2.setObjectName(u"CamSlide2")
        self.CamSlide2.setGeometry(QRect(390, 400, 321, 16))
        self.CamSlide2.setMaximum(479)
        self.CamSlide2.setOrientation(Qt.Horizontal)
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(390, 370, 171, 18))
        self.line_3 = QFrame(self.page_2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(350, 360, 20, 211))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(390, 510, 161, 18))
        self.IPCAM = QLineEdit(self.page_2)
        self.IPCAM.setObjectName(u"IPCAM")
        self.IPCAM.setGeometry(QRect(390, 530, 281, 26))
        self.ApplyIPCAM = QPushButton(self.page_2)
        self.ApplyIPCAM.setObjectName(u"ApplyIPCAM")
        self.ApplyIPCAM.setGeometry(QRect(680, 530, 31, 26))
        icon = QIcon()
        iconThemeName = u"Ok"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)
        
        self.ApplyIPCAM.setIcon(icon)
        self.CamList2 = QComboBox(self.page_2)
        self.CamList2.setObjectName(u"CamList2")
        self.CamList2.setGeometry(QRect(390, 470, 311, 26))
        self.CamList2.setEditable(False)
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(390, 440, 111, 18))
        self.ApplyCrop = QPushButton(self.page_2)
        self.ApplyCrop.setObjectName(u"ApplyCrop")
        self.ApplyCrop.setGeometry(QRect(20, 540, 151, 31))
        self.CropXStart = QSlider(self.page_2)
        self.CropXStart.setObjectName(u"CropXStart")
        self.CropXStart.setEnabled(False)
        self.CropXStart.setGeometry(QRect(20, 422, 151, 20))
        self.CropXStart.setMaximum(639)
        self.CropXStart.setValue(10)
        self.CropXStart.setOrientation(Qt.Horizontal)
        self.CropXEnd = QSlider(self.page_2)
        self.CropXEnd.setObjectName(u"CropXEnd")
        self.CropXEnd.setEnabled(False)
        self.CropXEnd.setGeometry(QRect(200, 422, 151, 20))
        self.CropXEnd.setMaximum(639)
        self.CropXEnd.setValue(100)
        self.CropXEnd.setOrientation(Qt.Horizontal)
        self.CropYStart = QSlider(self.page_2)
        self.CropYStart.setObjectName(u"CropYStart")
        self.CropYStart.setEnabled(False)
        self.CropYStart.setGeometry(QRect(20, 492, 151, 20))
        self.CropYStart.setMaximum(479)
        self.CropYStart.setValue(10)
        self.CropYStart.setOrientation(Qt.Horizontal)
        self.CropYEnd = QSlider(self.page_2)
        self.CropYEnd.setObjectName(u"CropYEnd")
        self.CropYEnd.setEnabled(False)
        self.CropYEnd.setGeometry(QRect(200, 492, 151, 20))
        self.CropYEnd.setMaximum(479)
        self.CropYEnd.setValue(100)
        self.CropYEnd.setOrientation(Qt.Horizontal)
        self.CropConEnable = QRadioButton(self.page_2)
        self.CropConEnable.setObjectName(u"CropConEnable")
        self.CropConEnable.setGeometry(QRect(20, 360, 171, 17))
        self.RevertCrop = QPushButton(self.page_2)
        self.RevertCrop.setObjectName(u"RevertCrop")
        self.RevertCrop.setGeometry(QRect(190, 540, 161, 31))
        self.label_18 = QLabel(self.page_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 380, 47, 13))
        self.label_19 = QLabel(self.page_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 400, 47, 13))
        self.label_20 = QLabel(self.page_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(200, 400, 47, 13))
        self.label_21 = QLabel(self.page_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 450, 47, 13))
        self.label_22 = QLabel(self.page_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 470, 47, 13))
        self.label_23 = QLabel(self.page_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(200, 470, 47, 13))
        self.KeepRatio = QCheckBox(self.page_2)
        self.KeepRatio.setObjectName(u"KeepRatio")
        self.KeepRatio.setGeometry(QRect(230, 360, 111, 17))
        self.DShow = QPushButton(self.page_2)
        self.DShow.setObjectName(u"DShow")
        self.DShow.setGeometry(QRect(604, 322, 101, 21))
        AppPages.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.LiveGraph_2 = QLabel(self.page_3)
        self.LiveGraph_2.setObjectName(u"LiveGraph_2")
        self.LiveGraph_2.setGeometry(QRect(0, 0, 720, 300))
        self.LiveGraph_2.setMaximumSize(QSize(16777215, 16777215))
        self.LiveGraph_2.setFrameShape(QFrame.StyledPanel)
        self.LiveGraph_2.setFrameShadow(QFrame.Raised)
        self.LiveGraph_2.setAlignment(Qt.AlignCenter)
        self.line_4 = QFrame(self.page_3)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(0, 300, 701, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.label_7 = QLabel(self.page_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 310, 58, 18))
        self.FirstPoint = QSlider(self.page_3)
        self.FirstPoint.setObjectName(u"FirstPoint")
        self.FirstPoint.setEnabled(False)
        self.FirstPoint.setGeometry(QRect(10, 370, 321, 16))
        self.FirstPoint.setAutoFillBackground(False)
        self.FirstPoint.setMaximum(639)
        self.FirstPoint.setOrientation(Qt.Horizontal)
        self.FirstPoint.setInvertedControls(False)
        self.Calibrate = QCheckBox(self.page_3)
        self.Calibrate.setObjectName(u"Calibrate")
        self.Calibrate.setGeometry(QRect(10, 310, 131, 24))
        self.label_12 = QLabel(self.page_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 340, 111, 18))
        self.label_13 = QLabel(self.page_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 400, 111, 18))
        self.SecondPoint = QSlider(self.page_3)
        self.SecondPoint.setObjectName(u"SecondPoint")
        self.SecondPoint.setEnabled(False)
        self.SecondPoint.setGeometry(QRect(10, 430, 321, 16))
        self.SecondPoint.setMaximum(639)
        self.SecondPoint.setOrientation(Qt.Horizontal)
        self.ApplyCal = QPushButton(self.page_3)
        self.ApplyCal.setObjectName(u"ApplyCal")
        self.ApplyCal.setGeometry(QRect(90, 563, 141, 26))
        self.label_14 = QLabel(self.page_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(150, 340, 121, 20))
        self.FPWL = QSpinBox(self.page_3)
        self.FPWL.setObjectName(u"FPWL")
        self.FPWL.setGeometry(QRect(280, 335, 51, 27))
        self.FPWL.setMaximum(999)
        self.FPWL.setValue(380)
        self.SPWL = QSpinBox(self.page_3)
        self.SPWL.setObjectName(u"SPWL")
        self.SPWL.setGeometry(QRect(280, 395, 51, 27))
        self.SPWL.setMaximum(999)
        self.SPWL.setValue(513)
        self.label_15 = QLabel(self.page_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(150, 400, 121, 20))
        self.line_5 = QFrame(self.page_3)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(340, 320, 20, 251))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.SplitChannel = QCheckBox(self.page_3)
        self.SplitChannel.setObjectName(u"SplitChannel")
        self.SplitChannel.setGeometry(QRect(360, 320, 231, 17))
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(360, 350, 191, 16))
        self.SpecMethod = QComboBox(self.page_3)
        self.SpecMethod.addItem("")
        self.SpecMethod.addItem("")
        self.SpecMethod.setObjectName(u"SpecMethod")
        self.SpecMethod.setGeometry(QRect(360, 370, 341, 22))
        self.label_24 = QLabel(self.page_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(150, 455, 121, 20))
        self.label_25 = QLabel(self.page_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(150, 515, 121, 20))
        self.label_26 = QLabel(self.page_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 455, 111, 18))
        self.label_27 = QLabel(self.page_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 515, 111, 18))
        self.FourthPoint = QSlider(self.page_3)
        self.FourthPoint.setObjectName(u"FourthPoint")
        self.FourthPoint.setEnabled(False)
        self.FourthPoint.setGeometry(QRect(10, 545, 321, 16))
        self.FourthPoint.setMaximum(639)
        self.FourthPoint.setOrientation(Qt.Horizontal)
        self.ThirdPoint = QSlider(self.page_3)
        self.ThirdPoint.setObjectName(u"ThirdPoint")
        self.ThirdPoint.setEnabled(False)
        self.ThirdPoint.setGeometry(QRect(10, 485, 321, 16))
        self.ThirdPoint.setAutoFillBackground(False)
        self.ThirdPoint.setMaximum(639)
        self.ThirdPoint.setOrientation(Qt.Horizontal)
        self.ThirdPoint.setInvertedControls(False)
        self.TPWL = QSpinBox(self.page_3)
        self.TPWL.setObjectName(u"TPWL")
        self.TPWL.setGeometry(QRect(280, 450, 51, 27))
        self.TPWL.setMaximum(999)
        self.TPWL.setValue(646)
        self.FoPWL = QSpinBox(self.page_3)
        self.FoPWL.setObjectName(u"FoPWL")
        self.FoPWL.setGeometry(QRect(280, 510, 51, 27))
        self.FoPWL.setMaximum(999)
        self.FoPWL.setValue(780)
        AppPages.addWidget(self.page_3)

        self.retranslateUi(AppPages)

        AppPages.setCurrentIndex(2)
        self.CamList.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(AppPages)
    # setupUi

    def retranslateUi(self, AppPages):
        AppPages.setWindowTitle(QCoreApplication.translate("AppPages", u"StackedWidget", None))
        self.LiveFeed.setText(QCoreApplication.translate("AppPages", u"TextLabel", None))
        self.LiveGraph.setText(QCoreApplication.translate("AppPages", u"TextLabel", None))
        self.label.setText(QCoreApplication.translate("AppPages", u" Webcam:", None))
        self.label_2.setText(QCoreApplication.translate("AppPages", u" Gr\u00e1fico:", None))
        self.label_4.setText(QCoreApplication.translate("AppPages", u" Configura\u00e7\u00f5es ", None))
        self.PixelRowEdit.setPlaceholderText(QCoreApplication.translate("AppPages", u"240", None))
        self.label_5.setText(QCoreApplication.translate("AppPages", u"  C\u00e2mera:", None))
        self.CamSnap.setText(QCoreApplication.translate("AppPages", u"Salvar Imagem", None))
        self.label_6.setText(QCoreApplication.translate("AppPages", u"  Gr\u00e1fico:", None))
        self.GraphCSV.setText(QCoreApplication.translate("AppPages", u"Salvar .csv", None))
        self.label_3.setText(QCoreApplication.translate("AppPages", u" Selecionar Linha:", None))
        self.GraphSnap.setText(QCoreApplication.translate("AppPages", u"Salvar Imagem", None))
        self.ToggleCursor.setText(QCoreApplication.translate("AppPages", u"Ativar Cursor:", None))
        self.ImgFlip.setText(QCoreApplication.translate("AppPages", u"Inverter Horiz.", None))
        self.label_10.setText(QCoreApplication.translate("AppPages", u"Comprimento de onda:", None))
        self.LNano.setText(QCoreApplication.translate("AppPages", u" ---.-- nm", None))
        self.label_17.setText(QCoreApplication.translate("AppPages", u"Intensidade(norm.):", None))
        self.LInt.setText(QCoreApplication.translate("AppPages", u" -.--", None))
        self.CamFeed.setText(QCoreApplication.translate("AppPages", u"TextLabel", None))
        self.label_8.setText(QCoreApplication.translate("AppPages", u"Selecionar linha de pixels:", None))
#if QT_CONFIG(tooltip)
        self.label_11.setToolTip(QCoreApplication.translate("AppPages", u"<html><head/><body><p>Adiciona uma webcam IP \u00e0 lista de c\u00e2meras</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_11.setText(QCoreApplication.translate("AppPages", u"Adicionar webcam por IP:", None))
        self.IPCAM.setText("")
        self.IPCAM.setPlaceholderText(QCoreApplication.translate("AppPages", u"Ex: 192.168.0.11:8888/video", None))
        self.ApplyIPCAM.setText(QCoreApplication.translate("AppPages", u"Ok", None))
        self.label_9.setText(QCoreApplication.translate("AppPages", u" Lista de c\u00e2meras:", None))
        self.ApplyCrop.setText(QCoreApplication.translate("AppPages", u"Aplicar Redimensionamento", None))
        self.CropConEnable.setText(QCoreApplication.translate("AppPages", u"Ativar Redimensionamento", None))
        self.RevertCrop.setText(QCoreApplication.translate("AppPages", u"Reverter Redimensionamento", None))
        self.label_18.setText(QCoreApplication.translate("AppPages", u"Eixo X:", None))
        self.label_19.setText(QCoreApplication.translate("AppPages", u"In\u00edcio:", None))
        self.label_20.setText(QCoreApplication.translate("AppPages", u"Fim:", None))
        self.label_21.setText(QCoreApplication.translate("AppPages", u"Eixo Y:", None))
        self.label_22.setText(QCoreApplication.translate("AppPages", u"In\u00edcio:", None))
        self.label_23.setText(QCoreApplication.translate("AppPages", u"Fim:", None))
        self.KeepRatio.setText(QCoreApplication.translate("AppPages", u"Manter Propor\u00e7\u00e3o", None))
        self.DShow.setText(QCoreApplication.translate("AppPages", u"Ajustes da Camera", None))
        self.LiveGraph_2.setText(QCoreApplication.translate("AppPages", u"TextLabel", None))
        self.label_7.setText("")
        self.Calibrate.setText(QCoreApplication.translate("AppPages", u"Ativar Calibra\u00e7\u00e3o", None))
        self.label_12.setText(QCoreApplication.translate("AppPages", u"Primeiro ponto:", None))
        self.label_13.setText(QCoreApplication.translate("AppPages", u"Segundo ponto:", None))
        self.ApplyCal.setText(QCoreApplication.translate("AppPages", u"Aplicar calibra\u00e7\u00e3o", None))
        self.label_14.setText(QCoreApplication.translate("AppPages", u"Comprimento (nm):", None))
        self.label_15.setText(QCoreApplication.translate("AppPages", u"Comprimento (nm):", None))
        self.SplitChannel.setText(QCoreApplication.translate("AppPages", u"Ativar divis\u00e3o de canais no arquivo .csv", None))
        self.label_16.setText(QCoreApplication.translate("AppPages", u"M\u00e9todo de obten\u00e7\u00e3o do espectro:", None))
        self.SpecMethod.setItemText(0, QCoreApplication.translate("AppPages", u"M\u00e9dia", None))
        self.SpecMethod.setItemText(1, QCoreApplication.translate("AppPages", u"Convers\u00e3o para escala de cinza", None))

        self.label_24.setText(QCoreApplication.translate("AppPages", u"Comprimento (nm):", None))
        self.label_25.setText(QCoreApplication.translate("AppPages", u"Comprimento (nm):", None))
        self.label_26.setText(QCoreApplication.translate("AppPages", u"Terceiro ponto:", None))
        self.label_27.setText(QCoreApplication.translate("AppPages", u"Quarto ponto:", None))
        self.List = returnCameraIndexes()
        for i in range(len(self.List)):
            self.CamList.addItem(f"Camera {i}")
            self.CamList2.addItem(f"Camera {i}")
    # retranslateUi

